#!/bin/bash -ue
filename="$1"
echo "Creating tarball..." >&2
tar caf "$filename.tar" "$filename"
echo "It's $(stat -c %s $filename.tar | numfmt --to=iec-i --suffix=B)" >&2
echo "Compressing..."
bar "$filename.tar" | xz -6 >"$filename.tar.xz"
echo "It compressed to $(stat -c %s $filename.tar.xz | numfmt --to=iec-i --suffix=B)" >&2
echo "Encrypting..." >&2
box <"$filename.tar.xz" >"$filename.boxed"
echo "Deleting old files..." >&2
rm -rf "$filename.tar" "$filename.tar.xz" "$filename"
echo "Done." >&2
echo ">>> Result placed in $filename.boxed <<<"
