#!/bin/bash
set -eux
trap 'rm -rf testdir' EXIT

success() {
  echo -e "\xe2\x9c\x93 $1" >&2
}

failure() {
  echo -e "\xe2\x9c\x97 $1" >&2
  exit 1
}

nacl=$(readlink -f nacl.debug)

#export LD_LIBRARY_PATH=/usr/local/lib

nacl() {
    valgrind --track-origins=yes -q "$nacl" "$@"
}

usage_err() {
    if "$@" 2>/dev/null; then
        failure "Should not have succeeded"
    else
        code=$?
        [ $? -ne 2 ] || failure "Should have returned 2, instead returned $code"
    fi
}

usage_err nacl
usage_err nacl asdf
usage_err nacl box-keypair
usage_err nacl box
usage_err nacl box-open

rm -rf testdir
mkdir testdir
pushd testdir
echo "Testing box..."
nacl box-keypair -p p1 -s s1
nacl box-keypair -p p2 -s s2
echo 'attack at dawn' >m1
nacl box -p p2 -s s1 -i m1 -o c
nacl box-open -p p1 -s s2 -i c -o m2
cmp --silent m1 m2 || failure "m1 and m2 differ"
success "Tested box"
popd

rm -rf testdir
mkdir testdir
pushd testdir
nacl secretbox-key -k k
echo hello >m1
nacl secretbox -k k -i m1 -o c
nacl secretbox-open -k k -i c -o m2
cmp --silent m1 m2 || failure "m1 and m2 differ"
success "secretbox"
popd

success "All tests successful"

