#!/bin/bash -ue

PATH=".:$PATH"

head -c 10000 /dev/urandom >sample
box password <sample >boxed
unbox password <boxed >unboxed
if diff sample unboxed >/dev/null
then
  echo "Success"
else
  echo "Failure"
fi

